// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package ru.ifmo.java.server.protocol;

public interface ArraySortRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.ifmo.java.server.protocol.ArraySortRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *    int32 size = 1;
   * </pre>
   *
   * <code>repeated int32 values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Integer> getValuesList();
  /**
   * <pre>
   *    int32 size = 1;
   * </pre>
   *
   * <code>repeated int32 values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <pre>
   *    int32 size = 1;
   * </pre>
   *
   * <code>repeated int32 values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  int getValues(int index);
}
