// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package ru.ifmo.java.server.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_ifmo_java_server_protocol_StarterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_ifmo_java_server_protocol_StarterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_ifmo_java_server_protocol_ArraySortRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_ifmo_java_server_protocol_ArraySortRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_ifmo_java_server_protocol_ArraySortResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_ifmo_java_server_protocol_ArraySortResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_ifmo_java_server_protocol_StatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_ifmo_java_server_protocol_StatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\022\034ru.ifmo.java.server.pr" +
      "otocol\"3\n\016StarterRequest\022\022\n\nserverType\030\001" +
      " \001(\t\022\r\n\005start\030\002 \001(\010\"\"\n\020ArraySortRequest\022" +
      "\016\n\006values\030\001 \003(\005\"#\n\021ArraySortResponse\022\016\n\006" +
      "values\030\001 \003(\005\"H\n\014StatResponse\022\016\n\006values\030\001" +
      " \003(\005\022\022\n\nhandleTime\030\002 \001(\001\022\024\n\014responseTime" +
      "\030\003 \001(\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_ifmo_java_server_protocol_StarterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_ifmo_java_server_protocol_StarterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_ifmo_java_server_protocol_StarterRequest_descriptor,
        new java.lang.String[] { "ServerType", "Start", });
    internal_static_ru_ifmo_java_server_protocol_ArraySortRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_ifmo_java_server_protocol_ArraySortRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_ifmo_java_server_protocol_ArraySortRequest_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_ru_ifmo_java_server_protocol_ArraySortResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_ifmo_java_server_protocol_ArraySortResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_ifmo_java_server_protocol_ArraySortResponse_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_ru_ifmo_java_server_protocol_StatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ru_ifmo_java_server_protocol_StatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_ifmo_java_server_protocol_StatResponse_descriptor,
        new java.lang.String[] { "Values", "HandleTime", "ResponseTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
