// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package ru.ifmo.java.server.protocol;

/**
 * Protobuf type {@code ru.ifmo.java.server.protocol.StarterRequest}
 */
public  final class StarterRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.ifmo.java.server.protocol.StarterRequest)
    StarterRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StarterRequest.newBuilder() to construct.
  private StarterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StarterRequest() {
    serverType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StarterRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StarterRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            serverType_ = s;
            break;
          }
          case 16: {

            start_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StarterRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StarterRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.ifmo.java.server.protocol.StarterRequest.class, ru.ifmo.java.server.protocol.StarterRequest.Builder.class);
  }

  public static final int SERVERTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object serverType_;
  /**
   * <code>string serverType = 1;</code>
   * @return The serverType.
   */
  public java.lang.String getServerType() {
    java.lang.Object ref = serverType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverType_ = s;
      return s;
    }
  }
  /**
   * <code>string serverType = 1;</code>
   * @return The bytes for serverType.
   */
  public com.google.protobuf.ByteString
      getServerTypeBytes() {
    java.lang.Object ref = serverType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_FIELD_NUMBER = 2;
  private boolean start_;
  /**
   * <pre>
   *    int32 requestsCount = 2;
   * </pre>
   *
   * <code>bool start = 2;</code>
   * @return The start.
   */
  public boolean getStart() {
    return start_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServerTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverType_);
    }
    if (start_ != false) {
      output.writeBool(2, start_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServerTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverType_);
    }
    if (start_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, start_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.ifmo.java.server.protocol.StarterRequest)) {
      return super.equals(obj);
    }
    ru.ifmo.java.server.protocol.StarterRequest other = (ru.ifmo.java.server.protocol.StarterRequest) obj;

    if (!getServerType()
        .equals(other.getServerType())) return false;
    if (getStart()
        != other.getStart()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getServerType().hashCode();
    hash = (37 * hash) + START_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStart());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ifmo.java.server.protocol.StarterRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.ifmo.java.server.protocol.StarterRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.ifmo.java.server.protocol.StarterRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.ifmo.java.server.protocol.StarterRequest)
      ru.ifmo.java.server.protocol.StarterRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StarterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StarterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.ifmo.java.server.protocol.StarterRequest.class, ru.ifmo.java.server.protocol.StarterRequest.Builder.class);
    }

    // Construct using ru.ifmo.java.server.protocol.StarterRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serverType_ = "";

      start_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StarterRequest_descriptor;
    }

    @java.lang.Override
    public ru.ifmo.java.server.protocol.StarterRequest getDefaultInstanceForType() {
      return ru.ifmo.java.server.protocol.StarterRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ru.ifmo.java.server.protocol.StarterRequest build() {
      ru.ifmo.java.server.protocol.StarterRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.ifmo.java.server.protocol.StarterRequest buildPartial() {
      ru.ifmo.java.server.protocol.StarterRequest result = new ru.ifmo.java.server.protocol.StarterRequest(this);
      result.serverType_ = serverType_;
      result.start_ = start_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.ifmo.java.server.protocol.StarterRequest) {
        return mergeFrom((ru.ifmo.java.server.protocol.StarterRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.ifmo.java.server.protocol.StarterRequest other) {
      if (other == ru.ifmo.java.server.protocol.StarterRequest.getDefaultInstance()) return this;
      if (!other.getServerType().isEmpty()) {
        serverType_ = other.serverType_;
        onChanged();
      }
      if (other.getStart() != false) {
        setStart(other.getStart());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.ifmo.java.server.protocol.StarterRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.ifmo.java.server.protocol.StarterRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object serverType_ = "";
    /**
     * <code>string serverType = 1;</code>
     * @return The serverType.
     */
    public java.lang.String getServerType() {
      java.lang.Object ref = serverType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serverType = 1;</code>
     * @return The bytes for serverType.
     */
    public com.google.protobuf.ByteString
        getServerTypeBytes() {
      java.lang.Object ref = serverType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serverType = 1;</code>
     * @param value The serverType to set.
     * @return This builder for chaining.
     */
    public Builder setServerType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serverType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serverType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerType() {
      
      serverType_ = getDefaultInstance().getServerType();
      onChanged();
      return this;
    }
    /**
     * <code>string serverType = 1;</code>
     * @param value The bytes for serverType to set.
     * @return This builder for chaining.
     */
    public Builder setServerTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serverType_ = value;
      onChanged();
      return this;
    }

    private boolean start_ ;
    /**
     * <pre>
     *    int32 requestsCount = 2;
     * </pre>
     *
     * <code>bool start = 2;</code>
     * @return The start.
     */
    public boolean getStart() {
      return start_;
    }
    /**
     * <pre>
     *    int32 requestsCount = 2;
     * </pre>
     *
     * <code>bool start = 2;</code>
     * @param value The start to set.
     * @return This builder for chaining.
     */
    public Builder setStart(boolean value) {
      
      start_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    int32 requestsCount = 2;
     * </pre>
     *
     * <code>bool start = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStart() {
      
      start_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.ifmo.java.server.protocol.StarterRequest)
  }

  // @@protoc_insertion_point(class_scope:ru.ifmo.java.server.protocol.StarterRequest)
  private static final ru.ifmo.java.server.protocol.StarterRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.ifmo.java.server.protocol.StarterRequest();
  }

  public static ru.ifmo.java.server.protocol.StarterRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StarterRequest>
      PARSER = new com.google.protobuf.AbstractParser<StarterRequest>() {
    @java.lang.Override
    public StarterRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StarterRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StarterRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StarterRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.ifmo.java.server.protocol.StarterRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

