// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package ru.ifmo.java.server.protocol;

public interface StatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.ifmo.java.server.protocol.StatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Integer> getValuesList();
  /**
   * <code>repeated int32 values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated int32 values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  int getValues(int index);

  /**
   * <code>double handleTime = 2;</code>
   * @return The handleTime.
   */
  double getHandleTime();

  /**
   * <code>double responseTime = 3;</code>
   * @return The responseTime.
   */
  double getResponseTime();
}
