// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package ru.ifmo.java.server.protocol;

/**
 * Protobuf type {@code ru.ifmo.java.server.protocol.StatResponse}
 */
public  final class StatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.ifmo.java.server.protocol.StatResponse)
    StatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StatResponse.newBuilder() to construct.
  private StatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StatResponse() {
    values_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StatResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StatResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              values_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            values_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              values_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              values_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 17: {

            handleTime_ = input.readDouble();
            break;
          }
          case 25: {

            responseTime_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        values_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.ifmo.java.server.protocol.StatResponse.class, ru.ifmo.java.server.protocol.StatResponse.Builder.class);
  }

  public static final int VALUES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList values_;
  /**
   * <code>repeated int32 values = 1;</code>
   * @return A list containing the values.
   */
  public java.util.List<java.lang.Integer>
      getValuesList() {
    return values_;
  }
  /**
   * <code>repeated int32 values = 1;</code>
   * @return The count of values.
   */
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <code>repeated int32 values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  public int getValues(int index) {
    return values_.getInt(index);
  }
  private int valuesMemoizedSerializedSize = -1;

  public static final int HANDLETIME_FIELD_NUMBER = 2;
  private double handleTime_;
  /**
   * <code>double handleTime = 2;</code>
   * @return The handleTime.
   */
  public double getHandleTime() {
    return handleTime_;
  }

  public static final int RESPONSETIME_FIELD_NUMBER = 3;
  private double responseTime_;
  /**
   * <code>double responseTime = 3;</code>
   * @return The responseTime.
   */
  public double getResponseTime() {
    return responseTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getValuesList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(valuesMemoizedSerializedSize);
    }
    for (int i = 0; i < values_.size(); i++) {
      output.writeInt32NoTag(values_.getInt(i));
    }
    if (handleTime_ != 0D) {
      output.writeDouble(2, handleTime_);
    }
    if (responseTime_ != 0D) {
      output.writeDouble(3, responseTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < values_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(values_.getInt(i));
      }
      size += dataSize;
      if (!getValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      valuesMemoizedSerializedSize = dataSize;
    }
    if (handleTime_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, handleTime_);
    }
    if (responseTime_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, responseTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.ifmo.java.server.protocol.StatResponse)) {
      return super.equals(obj);
    }
    ru.ifmo.java.server.protocol.StatResponse other = (ru.ifmo.java.server.protocol.StatResponse) obj;

    if (!getValuesList()
        .equals(other.getValuesList())) return false;
    if (java.lang.Double.doubleToLongBits(getHandleTime())
        != java.lang.Double.doubleToLongBits(
            other.getHandleTime())) return false;
    if (java.lang.Double.doubleToLongBits(getResponseTime())
        != java.lang.Double.doubleToLongBits(
            other.getResponseTime())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    hash = (37 * hash) + HANDLETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHandleTime()));
    hash = (37 * hash) + RESPONSETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getResponseTime()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ifmo.java.server.protocol.StatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.ifmo.java.server.protocol.StatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.ifmo.java.server.protocol.StatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.ifmo.java.server.protocol.StatResponse)
      ru.ifmo.java.server.protocol.StatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.ifmo.java.server.protocol.StatResponse.class, ru.ifmo.java.server.protocol.StatResponse.Builder.class);
    }

    // Construct using ru.ifmo.java.server.protocol.StatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      values_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      handleTime_ = 0D;

      responseTime_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.ifmo.java.server.protocol.Protocol.internal_static_ru_ifmo_java_server_protocol_StatResponse_descriptor;
    }

    @java.lang.Override
    public ru.ifmo.java.server.protocol.StatResponse getDefaultInstanceForType() {
      return ru.ifmo.java.server.protocol.StatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.ifmo.java.server.protocol.StatResponse build() {
      ru.ifmo.java.server.protocol.StatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.ifmo.java.server.protocol.StatResponse buildPartial() {
      ru.ifmo.java.server.protocol.StatResponse result = new ru.ifmo.java.server.protocol.StatResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        values_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.values_ = values_;
      result.handleTime_ = handleTime_;
      result.responseTime_ = responseTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.ifmo.java.server.protocol.StatResponse) {
        return mergeFrom((ru.ifmo.java.server.protocol.StatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.ifmo.java.server.protocol.StatResponse other) {
      if (other == ru.ifmo.java.server.protocol.StatResponse.getDefaultInstance()) return this;
      if (!other.values_.isEmpty()) {
        if (values_.isEmpty()) {
          values_ = other.values_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureValuesIsMutable();
          values_.addAll(other.values_);
        }
        onChanged();
      }
      if (other.getHandleTime() != 0D) {
        setHandleTime(other.getHandleTime());
      }
      if (other.getResponseTime() != 0D) {
        setResponseTime(other.getResponseTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.ifmo.java.server.protocol.StatResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.ifmo.java.server.protocol.StatResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList values_ = emptyIntList();
    private void ensureValuesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        values_ = mutableCopy(values_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 values = 1;</code>
     * @return A list containing the values.
     */
    public java.util.List<java.lang.Integer>
        getValuesList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(values_) : values_;
    }
    /**
     * <code>repeated int32 values = 1;</code>
     * @return The count of values.
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated int32 values = 1;</code>
     * @param index The index of the element to return.
     * @return The values at the given index.
     */
    public int getValues(int index) {
      return values_.getInt(index);
    }
    /**
     * <code>repeated int32 values = 1;</code>
     * @param index The index to set the value at.
     * @param value The values to set.
     * @return This builder for chaining.
     */
    public Builder setValues(
        int index, int value) {
      ensureValuesIsMutable();
      values_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 values = 1;</code>
     * @param value The values to add.
     * @return This builder for chaining.
     */
    public Builder addValues(int value) {
      ensureValuesIsMutable();
      values_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 values = 1;</code>
     * @param values The values to add.
     * @return This builder for chaining.
     */
    public Builder addAllValues(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, values_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 values = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValues() {
      values_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private double handleTime_ ;
    /**
     * <code>double handleTime = 2;</code>
     * @return The handleTime.
     */
    public double getHandleTime() {
      return handleTime_;
    }
    /**
     * <code>double handleTime = 2;</code>
     * @param value The handleTime to set.
     * @return This builder for chaining.
     */
    public Builder setHandleTime(double value) {
      
      handleTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double handleTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHandleTime() {
      
      handleTime_ = 0D;
      onChanged();
      return this;
    }

    private double responseTime_ ;
    /**
     * <code>double responseTime = 3;</code>
     * @return The responseTime.
     */
    public double getResponseTime() {
      return responseTime_;
    }
    /**
     * <code>double responseTime = 3;</code>
     * @param value The responseTime to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTime(double value) {
      
      responseTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double responseTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseTime() {
      
      responseTime_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.ifmo.java.server.protocol.StatResponse)
  }

  // @@protoc_insertion_point(class_scope:ru.ifmo.java.server.protocol.StatResponse)
  private static final ru.ifmo.java.server.protocol.StatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.ifmo.java.server.protocol.StatResponse();
  }

  public static ru.ifmo.java.server.protocol.StatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatResponse>
      PARSER = new com.google.protobuf.AbstractParser<StatResponse>() {
    @java.lang.Override
    public StatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StatResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.ifmo.java.server.protocol.StatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

